project_id = "qipbsrynlkcxrctwqgdf"

[functions.chat-with-sasha]
verify_jwt = true

[functions.scan-bakebook-entry]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.promote-admin]
verify_jwt = true

[functions.create-tip-jar-session]
verify_jwt = false

[functions.grant-promo-access]
verify_jwt = true

[functions.extend-tip-jar-session]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = true
